adjatives = [
    "Australian",
    "British",
    "Irish",
    "Scottish",
    "Chinese",
    "Indian",
    "Jamaican",
    "Jewish",
    "Mexican",
    "Muslim",
    "Pirate",
    "Native American",
    "Narcoleptic",
    "Russian",
    "Angry",
    "Ant-sized",
    "Apologetic",
    "Bashful",
    "Bewildered",
    "Bipolar",
    "Black",
    "Bored",
    "Combusting",
    "Confused",
    "Constipated",
    "Cyborg",
    "Dreary",
    "Sassy",
    "Sissy",
    "Salty",
    "Depressed",
    "Desperate",
    "Drunk",
    "Ejaculating",
    "Elderly",
    "Enthusiastic",
    "Evil",
    "Feminine",
    "Flamingly gay",
    "Ghostly",
    "Giant",
    "High",
    "Hungover",
    "Incredulous",
    "Insane",
    "Jealous",
    "Kidnapped",
    "Nazi",
    "Lost",
    "Masculine",
    "Melodramatic",
    "Old-timey",
    "Paranoid",
    "Poor",
    "Presidential",
    "Racist",
    "Rushed",
    "Self-loathing",
    "Sexy",
    "Shrinking",
    "Sick",
    "Sleepy",
    "Snooty",
    "Soprano",
    "Suffocating",
    "Thirsty",
    "Toddler",
    "Uncomfortable",
    "Uncoordinated",
    "Valley girl",
    "Vampire",
    "Zombie",
    ]
people = [
    ("Ace Ventura", "M"),
    ("Adam Sandler", "M"),
    ("Adolf Hitler", "M"),
    ("Antonio Banderas", "M"),
    ("Archie Bunker", "M"),
    ("Barack Obama", "M"),
    ("Bender \"Bending\" Rodriguez", "M"),
    ("Beyoncé", "F"),
    ("Galadriel", "F"),
    ("Stevie Nicks", "M"),
    ("Bernie Sanders", "M"),
    ("Hermione Granger", "F"),
    ("Amy Wong", "F"),
    ("Bill Clinton", "M"),
    ("Bill Cosby", "M"),
    ("Billy-Dee Williams", "M"),
    ("Bob Ross", "M"),
    ("Brett Favre", "M"),
    ("Burt Reynolds", "M"),
    ("Captain Jack Sparrow", "M"),
    ("Chef", "M"),
    ("Chewbacca", "M"),
    ("Clint Eastwood", "M"),
    ("Daffy Duck", "M"),
    ("Daniel Plainview", "M"),
    ("Danny Devito", "M"),
    ("David Attenborough", "M"),
    ("David Puddy", "M"),
    ("Doc. Emmet Brown", "M"),
    ("Doc. McCoy", "M"),
    ("Doctor Evil", "M"),
    ("Dolly Parton", "F"),
    ("Don Knotts", "M"),
    ("Donald Trump", "M"),
    ("Dr. Martin Luther King Jr.", "M"),
    ("Eddie Murphy", "M"),
    ("Elvis", "M"),
    ("Emperor Palpatine", "M"),
    ("Eric Cartman", "M"),
    ("Forest Gump", "M"),
    ("Fran Dresher", "F"),
    ("French Stewart", "M"),
    ("Gene Wilder", "M"),
    ("George Bush", "M"),
    ("Gimli", "M"),
    ("Glenn Quagmire", "M"),
    ("Gollum", "M"),
    ("Hank Hill", "M"),
    ("Harry Carry", "M"),
    ("Heath Ledger as the Joker", "M"),
    ("Hikaru Sulu", "M"),
    ("Hillary Clinton", "F"),
    ("Homer Simpson", "M"),
    ("Henry Kissinger", "M"),
    ("Hunter S. Thompson", "M"),
    ("Inigo Montoya", "M"),
    ("Jack Nickolson", "M"),
    ("James Earl Jones", "M"),
    ("James Hetfield", "M"),
    ("James T Kirk", "M"),
    ("James Woods", "M"),
    ("Jar-Jar Binks", "M"),
    ("Jerry Seinfeld", "M"),
    ("Jeff Goldblum", "M"),
    ("Jimmy Stewart", "M"),
    ("John Kennedy", "M"),
    ("John Madden", "M"),
    ("John Travolta", "M"),
    ("John Wayne at the First Thanksgiving", "M"),
    ("Kenny", "M"),
    ("Kermit", "M"),
    ("Krieger", "M"),
    ("Lt. Worf", "M"),
    ("Marge Simpson", "F"),
    ("Mario", "M"),
    ("Marlon Brando", "M"),
    ("Mary Poppins", "F"),
    ("Matthew Mcconaughey", "M"),
    ("Meatwad", "M"),
    ("Michael Kane", "M"),
    ("Michelle Obama", "F"),
    ("Montgomery \"Scotty\" Scott", "M"),
    ("Morgan Freeman", "M"),
    ("Mort Goldman", "M"),
    ("Mr. Garrison", "M"),
    ("Mr. Mackey", "M"),
    ("Mr. Spock", "M"),
    ("Navi", "F"),
    ("Newman", "M"),
    ("Nibbler", "M"),
    ("Oprah Winfrey", "F"),
    ("Ozzie Ozbourne", "M"),
    ("PacMan", "M"),
    ("Patrick Stewart", "M"),
    ("Paul Hogan", "M"),
    ("Peter Griffin", "M"),
    ("Pikachu", "M"),
    ("Popeye the Sailor Man", "M"),
    ("Ray Romano", "M"),
    ("Richard Nixon", "M"),
    ("Rick Moranis", "M"),
    ("Ricky Bobby", "M"),
    ("Robin Williams", "M"),
    ("Rod Serling", "M"),
    ("Rodney Dangerfield", "M"),
    ("Ron Burgundy", "M"),
    ("Samuel L. Jackson", "M"),
    ("Sara Silverman", "F"),
    ("Sarah Palin", "F"),
    ("Scooby-Doo", "M"),
    ("Sean Bean", "M"),
    ("Mr. Bean", "M"),
    ("Mad Hatter", "M"),
    ("Chesire Cat", "M"),
    ("Queen of Hearts", "F"),
    ("Taylor Swift", "F"),
    ("Sweet Dee", "F"),
    ("Old Greg", "M"),
    ("Maurice Moss", "M"),
    ("Sean Connery", "M"),
    ("Shaggy Rogers", "M"),
    ("Shaquille Oneal", "M"),
    ("Danarys Targaryon", "F"),
    ("John Snow", "M"),
    ("Ygritte", "F"),
    ("Shrek", "M"),
    ("Siri", "F"),
    ("Snoop Dogg", "M"),
    ("Optimus Prime", "M"),
    ("C-3P0", "M"),
    ("Spongebob", "M"),
    ("Steve Urkel", "M"),
    ("Steven Hawking", "M"),
    ("Stierling Archer", "M"),
    ("Sylvester the Cat", "M"),
    ("Cowardly Lion", "M"),
    ("Link", "M"),
    ("Alf", "M"),
    ("Princess Toadstool", "F"),
    ("cockroach guy from men in black", "M"),
    ("Tim Allen", "M"),
    ("Towlie", "M"),
    ("Traygun \"Gunner\" Mumford", "M"),
    ("Tree-beard", "M"),
    ("W.B Frog", "M"),
    ("Tweety Bird", "F"),
    ("Porky Pig", "M"),
    ("Liane Cartman", "F"),
    ("Mr. Ed", "M"),
    ("Beaver Cleaver", "M"),
    ("Arthur Fonzerelli", "M"),
    ("Gary Coleman", "M"),
    ("Mr. Feeny", "M"),
    ("Hypno-toad", "M"),
    ("Fez", "M"),
    ("Sheila Broflovski", "F"),
    ("Ronda Rousey", "F"),
    ("Buggs Bunny", "M"),
    ("Yosemite Sam", "M"),
    ("Betty Boop", "F"),
    ("Martha Stewart", "F"),
    ("Doctor Who", "M"),
    ("Samwise Gamgee", "M"),
    ("Jason Bourne", "M"),
    ("Will Hunting", "M"),
    ("Genie", "M"),
    ("Jessica Rabbit", "F"),
    ("Tywin Lannister", "M"),
    ("Veruca Salt", "F"),
    ("Walter Kronkite", "M"),
    ("Witch King of Angmar", "M"),
    ("John Cena", "M"),
    ("Hulk Hogan", "M"),
    ("Uhura", "F"),
    ("Vladamir Putin", "M"),
    ("Doctor John Zoidberg", "M"),
    ("Krusty the Clown", "M"),
    ("The Rock", "M"),
    ("Michael Weston", "M"),
    ("Sam Ax", "M"),
    ("Fiona", "F"),
    ("Will Smith", "M"),
    ("Garfield", "M"),
    ("Bill Murry", "M"),
    ("Micky Mouse", "M"),
    ("Goofy", "M"),
    ("Mon Mothma", "F"),
    ("Admiral Akbar", "M"),
    ("Selacious Krum", "M"),
    ("Princess Leia", "F"),
    ("R2-D2", "M"),
    ("Jabba the Hutt", "M"),
    ("Miley Cyrus", "F"),
    ("Billy-Ray Cyrus", "M"),
    ("Keanu Reeves", "M"),
    ("Bette Midler", "F"),
    ("Winston Churchill", "M"),
    ("Yoda", "M"),
    ("Yogi Bear", "M"),
    ("Ariel the Mermaid", "F"),
    ("Princess Jasmine", "F"),
    ("Dorothy", "F"),
    ("Wicked Witch", "F"),
    ("Flo (progressive insurance)", "F"),
    ("Doctor Cox", "M"),
    ("Cruella Devil", "F"),
    ("Ursula", "F"),
    ("Simba", "M"),
    ]
situations = [
    "about to break a week-long bout of constipation",
    "accepting an Academy award",
    "accepting an B.E.T. award",
    "accepting the futility of the human condition",
    "announcing a baseball game",
    "annoyingly reading all the road signs as they go by",
    "at a fancy dinner party, but everything is on fire",
    "at work",
    "battling the Rancor",
    "becoming a real boy",
    "being buried alive",
    "being constantly shit on by a flock of seagulls",
    "being electrocuted",
    "being very slowly flattened by a steam roller",
    "believes the government is after them",
    "breaking the news to someone that they have a terminal disease",
    "can't control the volume of {his} own voice",
    "can't find the remote-control",
    "caught in a running washing-machine",
    "coming to the realization that {he} is, in fact, two dwarves in an overcoat",
    "conducting a suicide bombing",
    "confessing to the murder of Princess Diana",
    "confessing to {his} best friend that {he} fucked their wife",
    "creeping through the sewers",
    "currently being accosted by a herd of dwarves",
    "currently eating a sandwich",
    "deciding between mayonaise and miracle whip",
    "deciding whether to make-out with {his} clone",
    "discovering {his} feminine side",
    "doesn't know what to do with {his} hands",
    "doesn't understand the point of Kwaanza",
    "doing some kung-fu fighting",
    "eating a variety of finely aged cheeses",
    "eating spicy food",
    "enslaving the world with an army of mecha-laser-squirrels",
    "explaining the virtues of a standing desk",
    "explaining why Donald Trump was really the better choice",
    "failing to learn the true meaning of Christmas",
    "falling down a flight of stairs",
    "falling on slippery ice",
    "getting a Bikini Wax",
    "giving candy to a baby, despite the parents' objections",
    "giving {his} father's eulogy, but really has to pee",
    "going antiquing",
    "going from birth to death in 30 seconds",
    "handling a hostage negotiation",
    "has an Alien from *Alien* erupting from {his} chest",
    "has ants all over {him}",
    "has to explain to everyone why they are turning into ants",
    "having a heart attack",
    "having explosive diarrhea",
    "having forgotten how nouns work",
    "having recently found out {he's} hot",
    "having recently found out {he's} ugly",
    "hitting on the waitress",
    "holding a lit stick of dynamite",
    "hunting for ghosts in a spooky mansion",
    "in free-fall",
    "in spaaaaaaaaaace!",
    "in the back of a humvee being chased by a T-Rex",
    "in the shower",
    "is going through childbirth",
    "is having an existential crisis",
    "is literally Hitler",
    "is sent to assassinate Hitler, but is slowly becoming sympathetic to his cause",
    "is trying to get {his} friend's opinion of Batman, without letting on that {he} *is* batman",
    "is witnessing the miracle of childbirth",
    "just inhaled helium",
    "leading a sing-along",
    "learning the true meaning of Christmas",
    "literally on fire",
    "literally stealing candy from a baby",
    "literally walking on sunshine, Whoa-oh",
    "losing basic motor skills",
    "making first-contact with aliens",
    "meeting {his} lover's parents for the first time, but cannot stop making sexual innuendos",
    "on a boat",
    "on an airplane next to a crying baby",
    "on the moon",
    "participating in a school shooting",
    "piloting the USS Enterprise",
    "plotting how to capture the Easter Bunny",
    "pretending to be a british person who is pretending to be american",
    "pretending to be a doctor in order to administer breast examinations",
    "proposing to the love of {his} life",
    "quietly getting blown under the table",
    "quietly giving oral in church and trying not to make a noise",
    "rage quitting",
    "realizing {he's} wasted {his} life",
    "realizing too late that {his} true treasure was {his} children",
    "recently decided to become a Def Jam Comic",
    "riding a roller-coaster",
    "riding a unicycle",
    "shitting out a pine-cone",
    "shoveling kittens into a wood-chipper",
    "singing \"My Heart Will go On\"",
    "singing a musical",
    "singing an opera",
    "slowly becoming a duck",
    "slowly being pulled toward a large fan",
    "soliciting butt-sex",
    "stuck in a traffic jam",
    "stuck in a tree",
    "stuck in quicksand",
    "suffering grievous injury",
    "talking directly to God",
    "talking to a kitty",
    "being the one musician at the Red Wedding who actually cares about giving a good performance",
    "throwing Gary Coleman into the sun",
    "trying cocaine for the first time, and loving it",
    "trying to _tamely_ explain how sex works to {his} child",
    "trying to buy a timeshare",
    "trying to conceal an erection",
    "trying to explain the plot of Breaking Bad",
    "trying to explain the rules of football, but only has a 10-second memory",
    "trying to explain why the Ring of Power should go to Gondor",
    "trying to find {his} own ass with two hands and a flashlight",
    "trying to justify the extermination of the Human Race",
    "trying to navigate a mine-field",
    "trying to over-compensate",
    "trying to sell a timeshare",
    "trying to steal honey from a bee-hive",
    "trying to swat away Bill Clinton's hand under the table during a meeting",
    "trying to walk back a Racist joke {he} just made",
    "turning into a werewolf",
    "turning tricks on the corner",
    "walking barefoot across a Lego strewn floor in the dark",
    "watching some personally disturbing pornography, but is still aroused",
    "weighing the pros and cons of blitzing a weak-side corner on third and long",
    "who is a high-school gym teacher who picks on the fat kids",
    "with a mouthfull of marshmallows",
    "rallying the Spartans at the battle of Thermopylae",
    "evolving into a being of pure conciousness",
    "trying to discreetly eat a particuarly crunchy taco at a funeral",
    "performing CPR",
    "trying to explain the concept of \"Love\" to a robot",
    "performing an ancient ritual to summon Lucifer himself",
    "auditioning for a role on a spanish soap-opera",
    "receiving a prostate exam",
    "giving a prostate exam",
    "discovering that Santa Clause is not real",
    "trying to re-live {his} glory days through {his} kids",
    "recalling the first time {he} made love",
    "politely declining gay sex",
    "knawing off {his} own leg to escape a bear trap",
    "posing as a high school kid as part of an elaborate plan to bring down a drug dealer",
    "trying to explain to Captain Planet why {he} deserves to be a Planeteer",
    "storming the beaches on D-Day, but is having second thoughts",
    ]
