adjatives = [
    "Australian",
    "British",
    "Chinese",
    "Indian",
    "Jamaican",
    "Jewish",
    "Mexican",
    "Muslim",
    "pirate",
    "Native American",
    "narcoleptic",
    "Russian",
    "angry",
    "ant-sized",
    "apologetic",
    "bashful",
    "bewildered",
    "bipolar",
    "black",
    "bored",
    "combusting",
    "confused",
    "constipated",
    "cyborg",
    "depressed",
    "desperate",
    "drunk",
    "ejaculating",
    "elderly",
    "enthusiastic",
    "evil",
    "feminine",
    "flamingly gay",
    "ghostly",
    "giant",
    "high",
    "hungover",
    "incredulous",
    "insane",
    "jealous",
    "kidnapped",
    "literally Hitler",
    "lost",
    "masculine",
    "melodramatic",
    "old-timey",
    "paranoid",
    "poor",
    "presidential",
    "racist",
    "rushed",
    "self-loathing",
    "sexy",
    "shrinking",
    "sick",
    "sleepy",
    "snooty",
    "soprano",
    "suffocating",
    "thirsty",
    "toddler",
    "uncomfortable",
    "uncoordinated",
    "valley girl",
    "vampire",
    "zombie",
]
people = [
    "Ace Ventura",
    "Adam Sandler",
    "Adolf Hitler",
    "Antonio Banderas",
    "Archie Bunker",
    "Barack Obama",
    "Bender \"Bending\" Rodriguez",
    "Bill Clinton",
    "Shaggy Rogers",
    "Bill Cosby",
    "Billy-Dee Williams",
    "Bob Ross",
    "Brett Favre",
    "Burt Reynolds",
    "Captain Jack Sparrow",
    "Chef",
    "Chewbacca",
    "Clint Eastwood",
    "Daniel Plainview (There will be blood)",
    "Danny Devito",
    "David Attenborough",
    "David Puddy",
    "Doc. McCoy",
    "Doctor Evil",
    "Don Knotts",
    "Donald Trump",
    "Daffy Duck",
    "Dr. Martin Luther King Jr.",
    "Eddie Murphy",
    "Emperor Palpatine",
    "Eric Cartman",
    "Forest Gump",
    "Fran Dresher",
    "French Stewart",
    "George Bush",
    "Gimli",
    "Glenn Quagmire",
    "Gollum",
    "Hank Hill",
    "Harry Carry",
    "Heath Ledger as the Joker",
    "Hikaru Sulu",
    "Homer Simpson",
    "Jack Nickolson",
    "James Earl Jones",
    "James Hetfield",
    "James T Kirk",
    "James Woods",
    "Jar-Jar Binks",
    "Jerry Seinfeld",
    "Jess Goldblum",
    "Jimmy Stewart",
    "John Kennedy",
    "John Madden",
    "John Travolta",
    "John Wayne at the First Thanksgiving",
    "Kenny",
    "Kermit",
    "Krieger",
    "Marge Simpson",
    "Mario",
    "Marlon Brando",
    "Matthew Mcconaughey",
    "Meatwad",
    "Michael Kane",
    "Montgomery \"Scotty\" Scott",
    "Morgan Freeman",
    "Mort Goldman",
    "Mr. Garrison",
    "Mr. Mackey",
    "Mr. Spock",
    "Navi",
    "Newman",
    "Nibbler",
    "Ozzie Ozbourne",
    "PacMan",
    "Patrick Stewart",
    "Paul Hogan",
    "Peter Griffin",
    "Pikachu",
    "Ray Romano",
    "Richard Nixon",
    "Rick Moranis",
    "Ricky Bobby",
    "Robin Williams",
    "Rod Serling",
    "Rodney Dangerfield",
    "Ron Burgundy",
    "Samuel L. Jackson",
    "Scooby-Doo",
    "Shaggy",
    "Sean Bean",
    "Sean Connery",
    "Shaquille Oneal",
    "Shrek",
    "Snoop Dogg",
    "Spongebob",
    "Steve Urkel",
    "Steven Hawking",
    "Stierling Archer",
    "Sylvester the Cat",
    "The Cowardly Lion",
    "The cockroach guy from men in black",
    "Towlie",
    "Traygun \"Gunner\" Mumford",
    "Tywin Lannister",
    "Walter Kronkite",
    "Lt. Worf",
    "Will Smith",
    "Winston Churchill",
    "Yoda",
    "Yogi Bear",
  ]
situations = [
    "At work",
    "Being electrocuted",
    "Believes the government is after them",
    "Can't control volume of own their voice",
    "Currently being accosted by a herd of dwarves",
    "Currently eating a sandwich",
    "Falling down a flight of stairs",
    "Getting a Bikini Wax",
    "Going from birth to death in 30 seconds",
    "Has an Alien from *Alien* erupting from their chest",
    "In the shower",
    "Suffering grievous injury",
    "Talking to a kitty",
    "Trying to _tamely_ explain how sex works to their child",
    "Trying to buy a timeshare",
    "Trying to explain the plot of Breaking Bad",
    "Trying to explain the rules of football, but only has a 10-second memory",
    "Losing basic motor skills",
    "On a boat",
    "In space",
    "On the moon",
    "Trying to explain why the Ring of Power should go to Gondor",
    "Trying to sell a timeshare",
    "Walking barefoot across a Lego strewn floor in the dark",
    "having explosive diarea",
    "having forgotten how nouns work",
    "having recently found out their hot",
    "having recently found out their ugly",
    "having a heart attack",
    "holding a lit stick of dynamite",
    "impersonating ______",
    "in free-fall",
    "just inhaled helium",
    "leading a sing-along",
    "literally on fire",
    "riding a unicycle",
    "singing an musical",
    "singing an opera",
    "slowly being pulled toward a large fan",
    "falling on slippery ice",
    "has ants all over them",
    "is having an existential crisis",
    "is going through childbirth",
    "on an airplane next to a crying baby",
    "creeping through the sewers",
    "accepting an Academy award",
    "accepting an B.E.T. award",
    "participating in a school shooting",
    "confessing to their best friend that they fucked their wife",
    "breaking the news to someone that they have a terminal disease",
    "shitting out a pine-cone",
    "about to break a week-long bout of constipation",
    "accepting the futility of the human condition",
    "realizing they've wasted their life",
    "realizing too late that their true treasure was their children",
    "confessing to the murder of Princess Diana",
    "Recently decided to become a Def Jam Comic",
    "Trying to walk back a Racist joke they just made",
    "Explaining why Donald Trump was really the better choice",
    "Has to explain to everyone why they are ants",
    "Throwing Gary Coleman into the sun",
    "Literally walking on sunshine, Whoa-oh",
    "Trying to find their own ass with two hands and a flashlight",
    "quietly getting blown under the table",
    "quietly giving oral in church and trying not to make a noise",
    "turning into a werewolf",
    "becoming a real boy",
    "discovering their feminine side",
    "Piloting the USS Enterprise",
    "Eating spicy food",
    "Being constantly shit on by a flock of seagulls",
    "Being very slowly flattened by a steam roller",
    "Annoyingly reading all the road signs as they go by",
    "Explaining the virtues of a standing desk",
    "With a mouthfull of marshmallows",
    "Singing \"My Heart Will go On\"",
    "Trying to over-compensate",
    "Trying to under-compensate",
    "Stuck in a traffic jam",
    "Announcing a baseball game",
    "Learning the true meaning of Christmas",
    "Failing to learn the true meaning of Christmas",
    "Doesn't understand the point of Kwaanza",
    "Slowly becoming a duck",
    "Doing some kung-fu fighting",
    "Hitting on the waitress",
    "Doesn't know what to do with their hands",
    "Trying to navigate a mine-field",
    "Going antiquing",
    "Rage quitting",
    "Watching some personally disturbing pornography, but is still aroused",
    "Trying to swat away Bill Clinton's hand under the table during a meeting",
    "Riding a roller-coaster",
    "Weighing the pros and cons of blitzing a weak-side corner on third and long",
    "Literally stealing candy from a baby",
    "Giving candy to a baby, despite the parents' objections",
    "Proposing to the love of their life",
    "Soliciting butt-sex",
    "Can't find the remote-control",
    "Stuck in a tree",
    "Handling a hostage negotiation",
    "Trying to steal honey from a bee-hive",
    "Trying to conceal an erection",
    "Hunting for ghosts in a spooky mansion",
    "Is trying to get their friends opinion of Batman, without letting on that they *are* batman",
    "Trying cocaine for the first time, and loving it",
    "Making first-contact with aliens",
    "Talking directly to God",
    "At a fancy dinner party, but everything is fire",
    "Being buried alive",
    "Stuck in quicksand",
    "Enslaving the world with an army of mecha-laser-squirrels",
]
