adjatives = [
    "Australian",
    "British",
    "Irish",
    "Scottish",
    "Chinese",
    "Indian",
    "Jamaican",
    "Jewish",
    "Mexican",
    "Muslim",
    "Pirate",
    "native American",
    "Narcoleptic",
    "russian",
    "Angry",
    "Ant-sized",
    "Apologetic",
    "Bashful",
    "Bewildered",
    "Bipolar",
    "Black",
    "Bored",
    "Combusting",
    "Confused",
    "Constipated",
    "Cyborg",
    "Dreary",
    "Sassy",
    "Sissy",
    "Salty",
    "Depressed",
    "Desperate",
    "Drunk",
    "Ejaculating",
    "Elderly",
    "Enthusiastic",
    "Evil",
    "Feminine",
    "Flamingly gay",
    "Ghostly",
    "Giant",
    "High",
    "Hungover",
    "Incredulous",
    "Insane",
    "Jealous",
    "Kidnapped",
    "Nazi"
    "Lost",
    "Masculine",
    "Melodramatic",
    "Old-timey",
    "Paranoid",
    "Poor",
    "Presidential",
    "Racist",
    "Rushed",
    "Self-loathing",
    "Sexy",
    "Shrinking",
    "Sick",
    "Sleepy",
    "Snooty",
    "Soprano",
    "Suffocating",
    "Thirsty",
    "Toddler",
    "Uncomfortable",
    "Uncoordinated",
    "Valley girl",
    "Vampire",
    "Zombie",
    ]
people = [
    "Ace Ventura",
    "Adam Sandler",
    "Adolf Hitler",
    "Antonio Banderas",
    "Archie Bunker",
    "Barack Obama",
    "Bender \"Bending\" Rodriguez",
    "Beyoncé",
    "Galadriel",
    "Stevie Nicks",
    "Hermione Granger",
    "Amy Wong",
    "Bill Clinton",
    "Bill Cosby",
    "Billy-Dee Williams",
    "Bob Ross",
    "Brett Favre",
    "Burt Reynolds",
    "Captain Jack Sparrow",
    "Chef",
    "Chewbacca",
    "Clint Eastwood",
    "Daffy Duck",
    "Daniel Plainview (There will be blood)",
    "Danny Devito",
    "David Attenborough",
    "David Puddy",
    "Doc. Emmet Brown",
    "Doc. McCoy",
    "Doctor Evil",
    "Dolly Parton",
    "Don Knotts",
    "Donald Trump",
    "Dr. Martin Luther King Jr.",
    "Eddie Murphy",
    "Elvis",
    "Emperor Palpatine",
    "Eric Cartman",
    "Forest Gump",
    "Fran Dresher",
    "French Stewart",
    "Gene Wilder",
    "George Bush",
    "Gimli",
    "Glenn Quagmire",
    "Gollum",
    "Hank Hill",
    "Harry Carry",
    "Heath Ledger as the Joker",
    "Hikaru Sulu",
    "Hillary Clinton",
    "Homer Simpson",
    "Hunter S. Thompson",
    "Inigo Montoya",
    "Jack Nickolson",
    "James Earl Jones",
    "James Hetfield",
    "James T Kirk",
    "James Woods",
    "Jar-Jar Binks",
    "Jerry Seinfeld",
    "Jess Goldblum",
    "Jimmy Stewart",
    "John Kennedy",
    "John Madden",
    "John Travolta",
    "John Wayne at the First Thanksgiving",
    "Kenny",
    "Kermit",
    "Krieger",
    "Lt. Worf",
    "Marge Simpson",
    "Mario",
    "Marlon Brando",
    "Mary Poppins",
    "Matthew Mcconaughey",
    "Meatwad",
    "Michael Kane",
    "Michelle Obama",
    "Montgomery \"Scotty\" Scott",
    "Morgan Freeman",
    "Mort Goldman",
    "Mr. Garrison",
    "Mr. Mackey",
    "Mr. Spock",
    "Navi",
    "Newman",
    "Nibbler",
    "Oprah Winfrey",
    "Ozzie Ozbourne",
    "PacMan",
    "Patrick Stewart",
    "Paul Hogan",
    "Peter Griffin",
    "Pikachu",
    "Popeye the Sailor Man",
    "Ray Romano",
    "Richard Nixon",
    "Rick Moranis",
    "Ricky Bobby",
    "Robin Williams",
    "Rod Serling",
    "Rodney Dangerfield",
    "Ron Burgundy",
    "Samuel L. Jackson",
    "Sara Silverman",
    "Sarah Palin",
    "Scooby-Doo",
    "Sean Bean",
    "Mr. Bean",
    "The Mad Hatter",
    "Chesire Cat",
    "Queen of Hearts",
    "Taylor Swift",
    "Sweet Dee",
    "Old Greg",
    "Maurice Moss",
    "Sean Connery",
    "Shaggy Rogers",
    "Shaggy",
    "Shaquille Oneal",
    "Danarys Targaryon",
    "John Snow",
    "Ygritte",
    "Shrek",
    "Siri",
    "Snoop Dogg",
    "Spongebob",
    "Steve Urkel",
    "Steven Hawking",
    "Stierling Archer",
    "Sylvester the Cat",
    "The Cowardly Lion",
    "Link",
    "Alf",
    "Princess Toadstool",
    "The cockroach guy from men in black",
    "Tim Allen",
    "Towlie",
    "Traygun \"Gunner\" Mumford",
    "Tree-beard",
    "The W.B Frog",
    "Tweety Bird",
    "Liane Cartman",
    "Mr. Ed",
    "Beaver Cleaver",
    "Arthur Fonzerelli",
    "Gary Coleman",
    "Mr. Feeny",
    "Hypnotoad",
    "Fez",
    "Sheila Broflovski",
    "Ronda Rousey",
    "Buggs Bunny",
    "Betty Boop",
    "Martha Stewart",
    "The Doctor",
    "Samwise Gamgee",
    "Jason Bourne",
    "Will Hunting",
    "The Genie",
    "Jessica Rabbit",
    "Tywin Lannister",
    "Veruca Salt (from Willy Wonka)",
    "Walter Kronkite",
    "The Witch king of Angmar",
    "John Cena",
    "Hulk Hogan",
    "Uhura",
    "Vladamir Putin",
    "Doctor John Zoidberg",
    "Krusty the Clown",
    "The Rock",
    "Michael Weston",
    "Sam Ax",
    "Fiona",
    "Will Smith",
    "Garfield",
    "Bill Murry",
    "Micky Mouse",
    "Goofy",
    "Mon Mothma",
    "Admiral Akbar",
    "Selacious Krum",
    "Princess Leia",
    "R2-D2",
    "Jabba the Hutt",
    "Miley Cyrus",
    "Billy-Ray Cyrus",
    "Keanu Reeves",
    "Bette Midler",
    "Winston Churchill",
    "Yoda",
    "Yogi Bear",
    "Ariel the Mermaid",
    "Princess Jasmine",
    "Dorothy",
    "The Wicked Witch",
    "Flo (progressive insurance)",
    "Doctor Cox",
    "Cruella Devil",
    "Ursula",
    "Simba",
    ]
situations = [
    "about to break a week-long bout of constipation",
    "accepting an Academy award",
    "accepting an B.E.T. award",
    "accepting the futility of the human condition",
    "announcing a baseball game",
    "annoyingly reading all the road signs as they go by",
    "at a fancy dinner party, but everything is on fire",
    "at work",
    "battling the Rancor",
    "becoming a real boy",
    "being buried alive",
    "being constantly shit on by a flock of seagulls",
    "being electrocuted",
    "being very slowly flattened by a steam roller",
    "believes the government is after them",
    "breaking the news to someone that they have a terminal disease",
    "can't control the volume of their own voice",
    "can't find the remote-control",
    "caught in a running washing-machine",
    "coming to the realization that they are, in fact, two dwarves in an overcoat",
    "conducting a suicide bombing",
    "confessing to the murder of Princess Diana",
    "confessing to their best friend that they fucked their wife",
    "creeping through the sewers",
    "currently being accosted by a herd of dwarves",
    "currently eating a sandwich",
    "deciding between mayonaise and miracle whip",
    "deciding whether to make-out with their clone",
    "discovering their feminine side",
    "doesn't know what to do with their hands",
    "doesn't understand the point of Kwaanza",
    "doing some kung-fu fighting",
    "eating a variety of finely aged cheeses",
    "eating spicy food",
    "enslaving the world with an army of mecha-laser-squirrels",
    "explaining the virtues of a standing desk",
    "explaining why Donald Trump was really the better choice",
    "failing to learn the true meaning of Christmas",
    "falling down a flight of stairs",
    "falling on slippery ice",
    "getting a Bikini Wax",
    "giving candy to a baby, despite the parents' objections",
    "giving their father's eulogy, but really has to pee",
    "going antiquing",
    "going from birth to death in 30 seconds",
    "handling a hostage negotiation",
    "has an Alien from *Alien* erupting from their chest",
    "has ants all over them",
    "has to explain to everyone why they are ants",
    "having a heart attack",
    "having explosive diarea",
    "having forgotten how nouns work",
    "having recently found out their hot",
    "having recently found out their ugly",
    "hitting on the waitress",
    "holding a lit stick of dynamite",
    "hunting for ghosts in a spooky mansion",
    "in free-fall",
    "in space",
    "in the back of a humvee being chased by a T-Rex",
    "in the shower",
    "is going through childbirth",
    "is having an existential crisis",
    "is literally Hitler",
    "is sent to assassinate Hitle, but is slowly becoming sympathetic to his cause",
    "is trying to get their friends opinion of Batman, without letting on that they *are* batman",
    "is witnessing the miracle of childbirth",
    "just inhaled helium",
    "leading a sing-along",
    "learning the true meaning of Christmas",
    "literally on fire",
    "literally stealing candy from a baby",
    "literally walking on sunshine, Whoa-oh",
    "losing basic motor skills",
    "making first-contact with aliens",
    "meeting their lover's parents for the first time, but cannot stop making sexual innuendos",
    "on a boat",
    "on an airplane next to a crying baby",
    "on the moon",
    "participating in a school shooting",
    "piloting the USS Enterprise",
    "plotting how to capture the Easter Bunny",
    "pretending to be a british person who is pretending to be american",
    "pretending to be a doctor in order to administer breast examinations",
    "proposing to the love of their life",
    "quietly getting blown under the table",
    "quietly giving oral in church and trying not to make a noise",
    "rage quitting",
    "realizing they've wasted their life",
    "realizing too late that their true treasure was their children",
    "recently decided to become a Def Jam Comic",
    "riding a roller-coaster",
    "riding a unicycle",
    "shitting out a pine-cone",
    "shoveling kittens into a wood-chipper",
    "singing \"My Heart Will go On\"",
    "singing an musical",
    "singing an opera",
    "slowly becoming a duck",
    "slowly being pulled toward a large fan",
    "soliciting butt-sex",
    "stuck in a traffic jam",
    "stuck in a tree",
    "stuck in quicksand",
    "suffering grievous injury",
    "talking directly to God",
    "talking to a kitty",
    "the one musician at the Red Wedding who actually cares about giving a good performance",
    "throwing Gary Coleman into the sun",
    "trying cocaine for the first time, and loving it",
    "trying to _tamely_ explain how sex works to their child",
    "trying to buy a timeshare",
    "trying to conceal an erection",
    "trying to explain the plot of Breaking Bad",
    "trying to explain the rules of football, but only has a 10-second memory",
    "trying to explain why the Ring of Power should go to Gondor",
    "trying to find their own ass with two hands and a flashlight",
    "trying to justify the extermination of the Human Race",
    "trying to navigate a mine-field",
    "trying to over-compensate",
    "trying to sell a timeshare",
    "trying to steal honey from a bee-hive",
    "trying to swat away Bill Clinton's hand under the table during a meeting",
    "trying to walk back a Racist joke they just made",
    "turning into a werewolf",
    "turning tricks on the corner",
    "walking barefoot across a Lego strewn floor in the dark",
    "watching some personally disturbing pornography, but is still aroused",
    "weighing the pros and cons of blitzing a weak-side corner on third and long",
    "who is a high-school gym teacher who picks on the fat kids",
    "with a mouthfull of marshmallows",
    ]
